// Le scritte dentro le immagini, in ogni lingua del sito.
export type Lingua = 'it' | 'en' | 'fr';

export const TESTI = {
  it: {
    solcoClaim: 'Trasparenti per scelta.',
    solcoDal: 'DAL 14.10',
    solcoColori: '(2) COLORI',
    solcoColoriSub: 'Buds 2 · dal 14 ottobre',
    solcoDentro: 'DENTRO (2)',
    solcoDentroSub: '23 pezzi. Nessuno di troppo.',
    solcoSuono: 'SUONO (2)',
    solcoSuonoTitolo: ['Il suono, spiegato', 'senza tecnicismi.'],
    solcoGiorni: 'GIORNI',
    solcoCountdown: 'Il conto alla rovescia è iniziato.',
    formaTitolo: ['Alle 7', 'la città', 'dorme.'],
    formaTuNo: 'Tu no.',
    formaScorri: 'Scorri →',
    formaPov: ['POV: sono le 7:00', 'e sei già qui'],
    osteriaTitolo: ['Il pescato', 'di oggi'],
    osteriaSub: 'scelto da Franco, alle 6:00',
    rivaEtichetta: 'Case study — 04',
    rivaTitolo: ['10 clienti.', '10 voci.'],
    rivaSub: 'Come teniamo separato il tono di ognuno.',
    rivaToni: ['Diretto', 'Caldo', 'Ironico', 'Tecnico', 'Gentile', 'Schietto', 'Energico', 'Curioso', 'Essenziale', 'Chiaro'],
    libreriaEtichetta: 'Consigli di settembre',
    libreriaTitolo: 'Tre libri per chi ha finito le vacanze,',
    libreriaChiusa: 'ma non la voglia di partire.',
    anteprima: ['Contenuti social con', 'la voce del tuo brand.'],
    anteprimaSub: 'Crei, organizzi e pianifichi i post con un’AI che conosce il tuo tone of voice.',
  },
  en: {
    solcoClaim: 'Transparent by choice.',
    solcoDal: 'FROM 14.10',
    solcoColori: '(2) COLOURS',
    solcoColoriSub: 'Buds 2 · from 14 October',
    solcoDentro: 'INSIDE (2)',
    solcoDentroSub: '23 parts. Not one too many.',
    solcoSuono: 'SOUND (2)',
    solcoSuonoTitolo: ['Sound, explained', 'without the jargon.'],
    solcoGiorni: 'DAYS',
    solcoCountdown: 'The countdown has begun.',
    formaTitolo: ['At 7', 'the city', 'sleeps.'],
    formaTuNo: 'You don’t.',
    formaScorri: 'Swipe →',
    formaPov: ['POV: it’s 7:00 a.m.', 'and you’re already here'],
    osteriaTitolo: ['Today’s', 'catch'],
    osteriaSub: 'picked by Franco at 6:00 a.m.',
    rivaEtichetta: 'Case study — 04',
    rivaTitolo: ['10 clients.', '10 voices.'],
    rivaSub: 'How we keep each one’s tone apart.',
    rivaToni: ['Direct', 'Warm', 'Witty', 'Technical', 'Kind', 'Blunt', 'Energetic', 'Curious', 'Essential', 'Clear'],
    libreriaEtichetta: 'September picks',
    libreriaTitolo: 'Three books for anyone whose holiday is over,',
    libreriaChiusa: 'but not their urge to travel.',
    anteprima: ['Social content in', 'your brand’s voice.'],
    anteprimaSub: 'Create, organise and plan your posts with an AI that knows your tone of voice.',
  },
  fr: {
    solcoClaim: 'Transparents par choix.',
    solcoDal: 'DÈS LE 14.10',
    solcoColori: '(2) COULEURS',
    solcoColoriSub: 'Buds 2 · dès le 14 octobre',
    solcoDentro: 'DEDANS (2)',
    solcoDentroSub: '23 pièces. Pas une de trop.',
    solcoSuono: 'SON (2)',
    solcoSuonoTitolo: ['Le son, expliqué', 'sans jargon.'],
    solcoGiorni: 'JOURS',
    solcoCountdown: 'Le compte à rebours a commencé.',
    formaTitolo: ['À 7 h', 'la ville', 'dort.'],
    formaTuNo: 'Pas toi.',
    formaScorri: 'Glisse →',
    formaPov: ['POV : il est 7 h', 'et tu es déjà là'],
    osteriaTitolo: ['La pêche', 'du jour'],
    osteriaSub: 'choisie par Franco à 6 h',
    rivaEtichetta: 'Étude de cas — 04',
    rivaTitolo: ['10 clients.', '10 voix.'],
    rivaSub: 'Comment nous gardons le ton de chacun.',
    rivaToni: ['Direct', 'Chaleureux', 'Ironique', 'Technique', 'Gentil', 'Franc', 'Énergique', 'Curieux', 'Essentiel', 'Clair'],
    libreriaEtichetta: 'Conseils de septembre',
    libreriaTitolo: 'Trois livres pour ceux qui ont fini leurs vacances,',
    libreriaChiusa: 'mais pas l’envie de partir.',
    anteprima: ['Vos contenus social media', 'avec la voix de votre marque.'],
    anteprimaSub: 'Créez, organisez et planifiez vos posts avec une IA qui connaît votre ton.',
  },
} satisfies Record<Lingua, Record<string, string | string[]>>;
